theme: jekyll-theme-minimal
title: Hehuan Ma
description: Ph.D. student at University of Texas at Arlington
logo: https://media-exp1.licdn.com/dms/image/C5603AQExEpuqgJFDNw/profile-displayphoto-shrink_200_200/0/1517799881773?e=1635984000&v=beta&t=pQgKJaTOgZMCksh-6EXqdcdblOx27TfqoCVz1Cqne4s
show_downloads: false
