theme: jekyll-theme-minimal
title: Hehuan Ma
description: Ph.D. student at University of Texas at Arlington
logo: https://github.com/hehuanma/hehuanma.github.io/blob/6753458e0ee5d7752153e5f3994c489264c9cda5/images/IMG_7813.JPG
show_downloads: false
